---
- name: Install pip
  yum: 
    name: "{{item}}"
    state: present
  with_items:
    - python-pip
  tags:
    - install

- name: Install env Docker
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - docker-py
  tags: 
    - install

- name: Clear
  docker_container:
    name: "{{item}}"
    state: absent
  with_items:
     - kong-database
     - kong
  tags: 
     - install
     - removeall

- name: Container kong-database use postgres is present
  docker_container:
    name: kong-database
    image: postgres:9.4
    state: started
    exposed_ports:
      - 5432
    published_ports:
      - 5432:5432
    env:
       POSTGRES_USER: kong
       POSTGRES_DB: kong
  tags:
    - install
    - run

- name: Migrate database for kong service
  docker_container:
    name: migrate
    image: kong:latest
    state: started
    links:
      kong-database:kong-database
    env:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    command: kong migrations up
  tags:
    - migrate
    - install

- name: Remove migrate command
  docker_container:
    name: migrate
    state: absent
  tags:
   - migrate
   - install

- name: Start Kong
  docker_container:
    name: kong
    image: kong
    state: present
    links:
      - kong-database:kong-database
    env:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    exposed_ports:
      - 8000
      - 8443
      - 8001
      - 8444
    published_ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
  tags:
    - install
    - run
