---
- name: install pip
  yum: 
    name: python-pip
    state: present

- name: pip install env Docker
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - docker-py

- name: Container kong-database use postgres is started
  docker_container:
    name: kong-database
    image: postgres:9.4
    state: started
    exposed_ports: 
      - 5432
    published_ports:
      - 5432:5432
    env:
       POSTGRES_USER: kong
       POSTGRES_DB: kong

- name: check whether kong was migrated or not
  command: echo "kong is not starting"
  args:
    warn: no
  register: resultkongmigrated
  changed_when: no
  failed_when: no

- include_tasks: migrate_kong.yml
  when: resultkongmigrated.rc === "kong is starting"
  static: no

- name: Start Kong
  docker_container:
    name: kong
    image: kong
    state: started
    links:
      - kong-database:kong-database
    env:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    exposed_ports:
      - 8000
      - 8443
      - 8001
      - 8444
    published_ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444

