---
- name: Install ZSH
  yum: 
    name: zsh 
    state: latest

- name: Install Oh my Zsh
  get_url: 
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh 
    dest: /home/install.sh
    mode: 0600

- name: copy zshrc conf
  template:
    src: zshrc.j2
    dest: ~/.zshrc
    owner: root
    group: root
    mode: 0644

- name: Run Script
  command: sh /home/install.sh

- name: run zsh as default
  command: chsh -s /bin/zsh

- name: remove file install  
  file:
    state: absent
    path: /home/install.sh 


