---
- name: Update EPEL
  yum: 
    name: epel-release
    state: present

- name: Install Util
  yum: 
    name: "{{item}}"
    state: present
  with_items:
   - git
   - tree
   - vim
   - tmux
   - openssh-server
   - htop
