---
- name: Install git
  yum: name=git state=present

- name: Install zsh
  yum: name=zsh state=present

- name: Install tree
  yum: name=tree state=present

- name: Install vim
  yum: name=vim state=present

- name: Install tmux
  yum: name=tmux state=present

- name: Install openssh
  yum: name=openssh-server state=present
