---
- name: Update package lists
  yum: name=* state=latest

- name: Update utilities prog
  import_tasks: install_util.yml

- name: check whether docker-ce has already installed
  command: rpm -q docker-ce
  args:
    warn: no
  register: resultdockerce
  changed_when: no
  failed_when: no

- name: check whether docker-compose has already installed
  command: docker-compose --version
  args:
    warn: no
  register: resultdockercompose
  changed_when: no
  failed_when: no

- name: check weather zsh has already installed
  command: rpm -q zsh
  args:
    warn: no
  register: resultzsh
  changed_when: no
  failed_when: no

- name: check zsh autosuggest still work
  command: grep "jtriley" ~/.zshrc
  args:
    warn: no
  register: resultzshsuggest
  changed_when: no
  failed_when: no

- include_tasks: install_docker.yml
  when: resultdockerce.rc
  static: no

- include_tasks: install_docker_compose.yml
  when: resultdockercompose.rc
  static: no

- include_tasks: install_zsh.yml
  when: resultzsh.rc
  static: no

- include_tasks: install_zsh_autosuggest.yml
  when: resultzshsuggest.rc
  static: no

- name: change the status of the docker daemon
  service:
    name: docker
    state: "{{docker_centos_state}}"
  when: docker_centos_state is not undefined

- name: make docker daemon enabled or disabled
  service:
    name: docker
    enabled: "{{docker_centos_enabled}}"
  when: docker_centos_enabled is not undefined

